20221030
YubaC/2810security.github.io pull request #1
Opened 2022-10-30 07:51 UTC by JNSGMS-28-10-AOS

1.在“近期事件”文件夹下添加文件“20221001国庆节”，并且在首页、近期事件网页内做了对应更新。
2.删除首页“近期事件”表格中倒数两行文字。
3.对首页中一些文字做了一些改动。

2022-11-01 04:17 UTC, YubaC commented on 近期事件/20221001国庆节.htm
> +<img src="20221001国庆节海报.jpg" width="500" height="661" alt=""/>
这里的图片没有了

2022-11-01 04:18 UTC, YubaC commented on index.htm
> -                    </li>
这里多删除了两行

2022-11-01 04:20 UTC, YubaC commented on 近期事件/20221001国庆节.htm
> +<img src="20221001国庆节海报.jpg" width="500" height="661" alt=""/>
另外图片最好做一下居中

2022-11-01 04:21 UTC, YubaC requested changes
请补上遗漏的图片。
具体问题请参考评论。

2022-11-04 13:09 UTC, JNSGMS-28-10-AOS commented on 近期事件/20221001国庆节.htm
> +<img src="20221001国庆节海报.jpg" width="500" height="661" alt=""/>
收到。立即更正。

2022-11-04 13:10 UTC, JNSGMS-28-10-AOS commented on index.htm
> -                    </li>
近期事件表格中事件太多了，我删除了几个。

2022-11-04 13:11 UTC, JNSGMS-28-10-AOS commented
已回复有关问题，造成的不便请见谅。

2022-11-04 13:31 UTC, JNSGMS-28-10-AOS commented
已完成对应修改，请重新审查。

2022-11-05 06:44 UTC, merged

2022-11-05 12:47 UTC, YubaC commented on index.htm
> -                    </li>
好。辛苦了。

2022-11-05 12:47 UTC, YubaC commented
感谢你的PR。
code review通过了。已合并。