20230521
YubaC/2810security.github.io pull request #19
Opened 2023-05-21 06:37 UTC by JNSGMS-28-10-AOS

1.首页：删除“近期事件”中第五条，并添加“庆祝劳动节”及其超链接。
2.“近期事件”文件夹：添加“20230501劳动节”文件夹及其包含的文件。
3.近期事件：添加“庆祝劳动节”及其超链接。

2023-05-21 12:23 UTC, YubaC requested changes
请按照Checks的“Echo bad links”的内容修复你的链接。

2023-06-18 13:34 UTC, JNSGMS-28-10-AOS commented
1.首页：删除“近期事件”中第五条，并添加“庆祝劳动节”及其超链接。
2.“近期事件”文件夹：添加“20230501劳动节”文件夹及其包含的文件。
3.近期事件：添加“庆祝劳动节”及其超链接。
4.修改了关于“庆祝劳动节”网页的超链接。

2023-06-18 14:58 UTC, JNSGMS-28-10-AOS commented
1.首页：删除“近期事件”中第五条，并添加“庆祝劳动节”及其超链接；删除“公示栏”中第五条，并添加“致夏季高考考生的一封信”及其超链接。
2.“近期事件”文件夹：添加“20230501劳动节”文件夹及其包含的文件。
3.近期事件：添加“庆祝劳动节”及其超链接。
4.修改了关于“庆祝劳动节”网页的超链接。
5.“公示栏”文件夹：添加“致夏季高考考生的一封信”文件夹及其包含的文件。
6.公示栏：添加“致夏季高考考生的一封信”及其超链接。

2023-06-18 23:11 UTC, YubaC approved these changes
感谢你的贡献。

2023-06-18 23:11 UTC, merged